apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow-dev

resources:
  - ../../base
  - secrets-rendered.yaml
  - env.yaml

# helmCharts:
#   - name: airflow
#     repo: https://airflow.apache.org
#     version: 1.16.0
#     releaseName: airflow-dev
#     namespace: airflow-dev
#     valuesFile: values-dev.yaml
#     includeCRDs: true
