apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    chart: airflow-1.16.0
    heritage: Helm
    release: airflow-dev
    tier: airflow
  name: airflow-dev-cleanup-rolebinding
  namespace: airflow-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-dev-cleanup-role
subjects:
  - kind: ServiceAccount
    name: airflow-dev-cleanup
    namespace: airflow-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    chart: airflow-1.16.0
    heritage: Helm
    release: airflow-dev
    tier: airflow
  name: airflow-dev-pod-launcher-rolebinding
  namespace: airflow-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-dev-pod-launcher-role
subjects:
  - kind: ServiceAccount
    name: airflow-dev-scheduler
    namespace: airflow-dev
  - kind: ServiceAccount
    name: airflow-dev-worker
    namespace: airflow-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    chart: airflow-1.16.0
    heritage: Helm
    release: airflow-dev
    tier: airflow
  name: airflow-dev-pod-log-reader-rolebinding
  namespace: airflow-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-dev-pod-log-reader-role
subjects:
  - kind: ServiceAccount
    name: airflow-dev-webserver
    namespace: airflow-dev
